# Generated by Django 3.2 on 2021-05-06 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=20)),
                ('data1', models.IntegerField()),
                ('data2', models.IntegerField()),
                ('data3', models.IntegerField()),
                ('data4', models.IntegerField()),
                ('data5', models.IntegerField()),
                ('data6', models.IntegerField()),
                ('data7', models.IntegerField()),
                ('data8', models.IntegerField()),
            ],
        ),
    ]
